### ISSUE TITLE
素材切り取り

### ISSUE THREAD

**Issue by mtsmtyuta** [totzyuta/zowa-cial#11]
まだもらえてなくてほしいもの
![screen shot 2018-12-11 at 15 57 17](https://user-images.githubusercontent.com/41325301/49997693-9eac2980-ffd5-11e8-800a-4260d30045d2.png)
![screen shot 2018-12-11 at 15 57 05](https://user-images.githubusercontent.com/41325301/49997695-a075ed00-ffd5-11e8-9575-7e266ca0bb90.png)
![screen shot 2018-12-11 at 15 56 55](https://user-images.githubusercontent.com/41325301/49997705-a4097400-ffd5-11e8-9e17-cd842bc8e7c4.png)

**Comment by mtsmtyuta** [comment]
![screen shot 2018-12-21 at 12 02 15](https://user-images.githubusercontent.com/41325301/50322456-54b4cd80-0518-11e9-8c59-7dc9e9ae1ff0.png)

**Comment by totzyuta** [comment]
指定いただいたもの、export設定して更新しました...！！確認お願いします。
